---

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: 'jdbc:mariadb://localhost:3308/maestro_talleres'
    username: root
    password: ramon1983
    driver-class-name: org.mariadb.jdbc.Driver

metadata:
  domain: comworkshops
  project_key: MASTERWWSC
  project_name: wsc-masterstrokes
  risk_profile: LOW (1.5)
  service: masterrp
