version: '3.4'
issue-tracking:
  - github
  - jira
endpoints:
  github:
    labels:
      IGNORE:
        - release-type/current
        - release-type/major
        - release-type/minor
        - release-type/patch
        - release-type/multi-hotfix
  jira:
    host: axinic.central.inditex.grp
    path: /jira/rest/api/2/issue
    server: https://axinic.central.inditex.grp/jira
repo-type: github
master-branch: main
included-paths: [ '/code' ]
